// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "&rOQOPOOOfOQO'#C_OkOQO'#CdOpOQO'#CeOuOQO'#CfOzOPO'#CcO!POPO'#ChOOOO'#Cb'#CbOOOO'#Cl'#ClOTOPO'#C^O!UOPO'#CiOOOO'#C^'#C^OTOPO'#C^OOOO'#Cj'#CjQQOPOOO!ZOQO,58yO!ZOQO,59OO!ZOQO,59PO!`OPO,59QOOOO,58},58}OOOO,59S,59SOOOO-E6j-E6jOOOO,58x,58xOOOO,59T,59TOTOPO,58xOOOO-E6h-E6hOOOO'#C`'#C`O!eOQO1G.eO!jOQO1G.jO!oOQO1G.kOOOO'#Ck'#CkO!tOPO'#CgO!|OPO1G.lOOOO1G.d1G.dO!`OPO7+$POOOO7+$U7+$UOOOO7+$V7+$VOOOO-E6i-E6iO!ZOQO7+$WO#ROPO'#CaO#ZOPO<<GkO#`OQO<<GrOOOOAN=VAN=VOOOOAN=^AN=^",
  stateData: "#e~ObPOfUOgYOhQOiROjSO~Oc_O~Oc`O~OcaO~OcbO~OgcO~OgdO~OggO~OdjO~OfnO~OerO~OesO~OetO~OfnOkZX~OkvO~OfnOgTX~OgzO~Oe{O~O",
  goto: "#ZaPPbfjvy!Q!X!X!X!`!Q!c!n!t#OT]O^T[O^Qk_Ql`QmaRyvRxrZWOX[^hZVOX[^hZTOX[^hRpbSZO^SfX[RqhQ^ORi^QobSuowRwrSXO^SeXhRh[",
  nodeNames: "⚠ Document Block Declaration Name Title Line Annotation Invocation Append Edge Label ContentLine BlankLine",
  maxTerm: 27,
  skippedNodes: [0],
  repeatNodeCount: 3,
  tokenData: "'^~RkOY!vYZ#qZ]!v^{!v{|#v|}#{}!O!v!O!P$Q!P!Q!v!Q![$V![!^!v!_!`!v!`!a%f!a!c!v!c!}$V!}#O%k#O#P!v#P#Q&b#Q#R!v#R#S$V#S#T!v#T#o$V#o#r!v#r#s'X#s;'S!v;'S;=`#k<%lO!vP!{YfPOY!vZ]!v^{!v}!O!v!P!^!v!_!`!v!a#r!v#s;'S!v;'S;=`#k<%lO!vP#nP;=`<%l!v~#vOg~~#{Oi~~$QOk~~$VOb~R$^bdQfPOY!vZ]!v^{!v}!O!v!P!Q!v!Q![$V![!^!v!_!`!v!a!c!v!c!}$V!}#R!v#R#S$V#S#T!v#T#o$V#o#r!v#s;'S!v;'S;=`#k<%lO!v~%kOh~R%rYcQfPOY!vZ]!v^{!v}!O!v!P!^!v!_!`!v!a#r!v#s;'S!v;'S;=`#k<%lO!vR&iYeQfPOY!vZ]!v^{!v}!O!v!P!^!v!_!`!v!a#r!v#s;'S!v;'S;=`#k<%lO!v~'^Oj~",
  tokenizers: [0, 1],
  topRules: {"Document":[0,1]},
  tokenPrec: 0
})
