// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Document = 1,
  Block = 2,
  Declaration = 3,
  Name = 4,
  Title = 5,
  Line = 6,
  Annotation = 7,
  Invocation = 8,
  Append = 9,
  Edge = 10,
  Label = 11,
  ContentLine = 12,
  BlankLine = 13
